# A dependabot configuration
#
# 1) it should update my github actions to the latest version every day
# 2) it should update my terraform providers every day

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
